### ISSUE TITLE
how to use in visual studio 2015?

### ISSUE THREAD

**Issue by mooreniemi** [TinyBlueRobots/NancyFs#1]
Forgive me, total .NET newb trying to try out your project. I used the "open from source control" in Visual Studio 2015. It failed to load with this message:

```
C:\Users\bigba_000\Source\Repos\nancyfs\src\NancyFs\NancyFs.fsproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\bigba_000\Source\Repos\nancyfs\src\NancyFs\NancyFs.fsproj
```

Can you tell me what the recommended way of using this project is in VS2015? Also, any chance you could export it as a template to be used through the Extensions gallery?

**Comment by mooreniemi** [comment]
I took my waddling newb steps and so far "resolved" this:

I edited the NancyFs.fsproj file to not reference the import you had listed, and it built just fine. IIUC the problem would come from you working outside VS, and thus needing that lib, right?

**Comment by JonCanning** [comment]
Ah yes, Microsoft.WebApplication.targets needs to be added as a package. I'll do that.
